export const category = [
  'Account & Finance',
  'Technology',
  'Medical & Nurse',
  'Marketing & Sales',
  'Design Jobs',
  'Transportation',
  'Development',
  'Receptionist Job',
  'Non-Profit Orag',
  'Architect Jobs',
  'Customer Service',
  'Education & Teaching',
  'Human Resources',
  'Legal Jobs',
  'Media & Communication',
];

export const titles = [
  {
    category: 'Development',
    domain: ['Software Engineer', 'Web Developer', 'Mobile App Developer'],
  },
  {
    category: 'Architect Jobs',
    domain: [
      'Software Architect',
      'Solution Architect',
      'Enterprise Architect',
    ],
  },
  {
    category: 'Account & Finance',
    domain: [
      'Accountant',
      'Financial Analyst',
      'Bookkeeper',
      'Financial Controller',
      'Tax Accountant',
      'Investment Analyst',
      'Auditor',
      'Payroll Specialist',
    ],
  },
  {
    category: 'Technology',
    domain: [
      'IT Specialist',
      'Network Administrator',
      'Systems Analyst',
      'Full-Stack Developer',
      'Data Scientist',
      'Cybersecurity Analyst',
      'Cloud Solutions Architect',
      'DevOps Engineer',
    ],
  },
  {
    category: 'Medical & Nurse',
    domain: [
      'Medical Doctor',
      'Nurse Practitioner',
      'Registered Nurse',
      'Medical Lab Technician',
      'Physician Assistant',
      'Occupational Therapist',
      'Pharmacist',
      'Certified Nursing Assistant',
    ],
  },
  {
    category: 'Marketing & Sales',
    domain: [
      'Marketing Manager',
      'Sales Representative',
      'Digital Marketer',
      'Digital Marketing Manager',
      'Sales Manager',
      'Brand Strategist',
      'Social Media Specialist',
      'E-commerce Manager',
    ],
  },
  {
    category: 'Design Jobs',
    domain: [
      'Graphic Designer',
      'UI/UX Designer',
      'Product Designer',
      'Motion Graphics Designer',
      'Industrial Designer',
      'User Researcher',
      'UX Writer',
      'Visual Merchandiser',
    ],
  },
  {
    category: 'Transportation',
    domain: [
      'Truck Driver',
      'Delivery Driver',
      'Forklift Operator',
      'Delivery Driver Supervisor',
      'Logistics Coordinator',
      'Flight Attendant',
      'Ship Captain',
      'Warehouse Manager',
    ],
  },
  {
    category: 'Receptionist Job',
    domain: [
      'Front Desk Receptionist',
      'Office Assistant',
      'Administrative Receptionist',
      'Hotel Front Desk Agent',
      'Medical Office Receptionist',
      'Legal Receptionist',
      'Corporate Receptionist',
      'School Receptionist',
    ],
  },
  {
    category: 'Non-Profit Org',
    domain: [
      'Fundraising Manager',
      'Program Coordinator',
      'Community Outreach Specialist',
      'Grant Writer',
      'Volunteer Coordinator',
      'Community Development Manager',
      'Program Manager',
      'Fundraising Coordinator',
    ],
  },
  {
    category: 'Customer Service',
    domain: [
      'Customer Service Representative',
      'Customer Success Manager',
      'Call Center Agent',
      'Customer Experience Specialist',
      'Technical Support Specialist',
    ],
  },
  {
    category: 'Education & Teaching',
    domain: [
      'Teacher',
      'Professor',
      'Tutor',
      'Instructional Designer',
      'Education Coordinator',
    ],
  },
  {
    category: 'Human Resources',
    domain: [
      'HR Manager',
      'Recruitment Specialist',
      'Training and Development Coordinator',
      'HR Business Partner',
      'Compensation and Benefits Analyst',
    ],
  },
  {
    category: 'Legal Jobs',
    domain: [
      'Lawyer',
      'Legal Assistant',
      'Paralegal',
      'Legal Consultant',
      'Legal Operations Manager',
    ],
  },
  {
    category: 'Media & Communication',
    domain: [
      'Journalist',
      'Public Relations Specialist',
      'Content Writer',
      'Media Planner',
      'Social Media Manager',
    ],
  },
];
