export const category = [
  'Account & Finance',
  'Development & Technology',
  'Medical & Nurse',
  'Marketing & Sales',
  'Design Jobs',
  'Transportation',
  'Receptionist Job',
  'Non-Profit Orag',
  'Architect Jobs',
  'Customer Service',
  'Education & Teaching',
  'Human Resources',
  'Legal Jobs',
  'Media & Communication',
];

export const titles = [
  {
    category: 'Account & Finance',
    domain: [
      'Accountant',
      'Financial Analyst',
      'Bookkeeper',
      'Financial Controller',
      'Tax Accountant',
      'Investment Analyst',
      'Auditor',
      'Payroll Specialist',
      'Financial Manager',
      'Budget Analyst',
      'Credit Analyst',
      'Tax Specialist',
      'Investment Banker',
      'Treasury Analyst',
      'Chief Financial Officer (CFO)',
      'Internal Auditor',
      'Cost Accountant',
      'Financial Consultant',
    ],
  },
  {
    category: 'Development & Technology',
    domain: [
      'Software Engineer',
      'Web Developer',
      'Mobile App Developer',
      'Game Developer',
      'Front-End Developer',
      'Back-End Developer',
      'UI/UX Developer',
      'Database Developer',
      'Embedded Systems Developer',
      'DevOps Engineer',
      'Quality Assurance (QA) Engineer',
      'Software Tester',
      'Systems Analyst',
      'Software Architect',
      'Cloud Solutions Engineer',
      'Machine Learning Engineer',
      'Artificial Intelligence (AI) Developer',
      'Augmented Reality (AR) Developer',
      'Virtual Reality (VR) Developer',
      'Blockchain Developer',
      'Robotics Engineer',
      'Automation Engineer',
      'IT Specialist',
      'Network Administrator',
      'Cybersecurity Analyst',
      'Data Scientist',
      'Full-Stack Developer',
      'IT Support Specialist',
      'Systems Administrator',
      'Cloud Solutions Architect',
      'Network Engineer',
      'Hardware Engineer',
      'Technology Consultant',
      'Data Analyst',
      'Business Intelligence (BI) Developer',
      'UI/UX Designer',
      'Graphic Designer',
      'Network Security Engineer',
      'Software Development Manager',
      'Web Development Manager',
      'Technology Sales Specialist',
      'Node.js Developer',
      'React Developer',
      'Angular Developer',
      'Vue.js Developer',
      'Python Developer',
      'Java Developer',
      'C# Developer',
      'PHP Developer',
      'Ruby Developer',
      'iOS Developer',
      'Android Developer',
      'Unity Developer',
      'Gameplay Programmer',
      'Backend API Developer',
      'Database Administrator',
      'Data Engineer',
      'Cloud Infrastructure Engineer',
      'AI/ML Researcher',
      'AR/VR Content Developer',
      'Software Architect',
      'Solution Architect',
      'Enterprise Architect',
      'Cloud Solutions Architect',
      'Data Architect',
      'Infrastructure Architect',
      'Application Architect',
      'Network Architect',
      'Security Architect',
      'Big Data Architect',
      'AI Solutions Architect',
      'Integration Architect',
      'Web Application Architect',
      'Mobile Application Architect',
      'Technical Architect',
      'Database Architect',
      'Information Architect',
      'Systems Architect',
      'Enterprise Integration Architect',
      'Digital Solutions Architect',
      'Business Process Architect',
      'Data Warehouse Architect',
      'Cloud Infrastructure Architect',
      'API Architect',
      'AR/VR Solutions Architect',
      'DevOps Architect',
      'Machine Learning Architect',
      'IoT Solutions Architect',
      'Embedded Systems Architect',
      'Microservices Architect',
      'CRM Solutions Architect',
      'ERP Solutions Architect',
      'IT Security Architect',
      'Multi-Cloud Solutions Architect',
      'Blockchain Solutions Architect',
      'UX/UI Architect',
      'Data Governance Architect',
      'IT Infrastructure Architect',
      'Mobile Solutions Architect',
      'Application Integration Architect',
      'Data Migration Architect',
      'Service-Oriented Architecture (SOA) Architect',
      'Digital Transformation Architect',
      'Virtualization Architect',
      'Content Management Architect',
      'Cloud Security Architect',
      'Business Intelligence Architect',
      'Customer Experience (CX) Architect',
      'Robotics Solutions Architect',
      'Network Security Architect',
      'Information Security Architect',
      'AR/VR Content Architect',
      'Systems Integration Architect',
      'Edge Computing Architect',
      'IoT Security Architect',
      'Data Privacy Architect',
      'Embedded Software Architect',
      'Cloud Migration Architect',
      'Microservices Integration Architect',
      'Data Analytics Architect',
      'Data Modeling Architect',
      'Systems Development Architect',
      'Infrastructure Design Architect',
      'Enterprise Data Architect',
      'Web Solutions Architect',
      'Mobile App Integration Architect',
      'AI Model Architect',
      'Cloud Governance Architect',
      'Cloud Infrastructure Design Architect',
      'Big Data Integration Architect',
      'IT Operations Architect',
      'Data Lake Architect',
      'Data Warehousing Architect',
      'Business Continuity Architect',
      'Application Security Architect',
      'Cloud Strategy Architect',
      'IT Service Management Architect',
    ],
  },
  {
    category: 'Medical & Nurse',
    domain: [
      'Medical Doctor',
      'Nurse Practitioner',
      'Registered Nurse',
      'Medical Lab Technician',
      'Physician Assistant',
      'Occupational Therapist',
      'Pharmacist',
      'Certified Nursing Assistant',
      'Medical Researcher',
      'Clinical Nurse Specialist',
      'Surgical Nurse',
      'Pediatrician',
      'Radiologic Technologist',
      'Psychiatrist',
      'Physical Therapist',
      'Dental Hygienist',
      'Medical Transcriptionist',
      'Home Health Aide',
      'Neonatal Nurse',
      'Phlebotomist',
      'Medical Coder',
      'Clinical Psychologist',
      'Nurse Anesthetist',
      'Cardiac Nurse',
      'Dental Assistant',
      'Respiratory Therapist',
      'Paramedic',
      'Mental Health Counselor',
    ],
  },
  {
    category: 'Marketing & Sales',
    domain: [
      'Marketing Manager',
      'Sales Representative',
      'Digital Marketer',
      'Digital Marketing Manager',
      'Sales Manager',
      'Brand Strategist',
      'Social Media Specialist',
      'E-commerce Manager',
      'Market Research Analyst',
      'Advertising Manager',
      'Public Relations Manager',
      'Content Marketing Specialist',
      'SEO Specialist',
      'Email Marketing Coordinator',
      'Sales Executive',
      'Retail Sales Associate',
      'Event Planner',
      'Customer Success Specialist',
    ],
  },
  {
    category: 'Design Jobs',
    domain: [
      'Graphic Designer',
      'UI/UX Designer',
      'Product Designer',
      'Motion Graphics Designer',
      'Industrial Designer',
      'User Researcher',
      'UX Writer',
      'Visual Merchandiser',
      'Web Designer',
      'Illustrator',
      'Brand Identity Designer',
      'Interaction Designer',
      'Game Designer',
      'Packaging Designer',
      'Experience Designer',
      'Motion Designer',
      '3D Artist',
      'Interior Designer',
    ],
  },
  {
    category: 'Transportation',
    domain: [
      'Truck Driver',
      'Delivery Driver',
      'Forklift Operator',
      'Delivery Driver Supervisor',
      'Logistics Coordinator',
      'Flight Attendant',
      'Ship Captain',
      'Warehouse Manager',
    ],
  },
  {
    category: 'Receptionist Job',
    domain: [
      'Front Desk Receptionist',
      'Office Assistant',
      'Administrative Receptionist',
      'Hotel Front Desk Agent',
      'Medical Office Receptionist',
      'Legal Receptionist',
      'Corporate Receptionist',
      'School Receptionist',
    ],
  },
  {
    category: 'Non-Profit Org',
    domain: [
      'Fundraising Manager',
      'Program Coordinator',
      'Community Outreach Specialist',
      'Grant Writer',
      'Volunteer Coordinator',
      'Community Development Manager',
      'Program Manager',
      'Fundraising Coordinator',
    ],
  },
  {
    category: 'Customer Service',
    domain: [
      'Customer Service Representative',
      'Customer Success Manager',
      'Call Center Agent',
      'Customer Experience Specialist',
      'Technical Support Specialist',
    ],
  },
  {
    category: 'Education & Teaching',
    domain: [
      'Teacher',
      'Professor',
      'Tutor',
      'Instructional Designer',
      'Education Coordinator',
    ],
  },
  {
    category: 'Human Resources',
    domain: [
      'HR Manager',
      'Recruitment Specialist',
      'Training and Development Coordinator',
      'HR Business Partner',
      'Compensation and Benefits Analyst',
    ],
  },
  {
    category: 'Legal Jobs',
    domain: [
      'Lawyer',
      'Legal Assistant',
      'Paralegal',
      'Legal Consultant',
      'Legal Operations Manager',
    ],
  },
  {
    category: 'Media & Communication',
    domain: [
      'Journalist',
      'Public Relations Specialist',
      'Content Writer',
      'Media Planner',
      'Social Media Manager',
    ],
  },
];
